// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCourseVideo = "course_video"

// UserAccount mapped from table <user_account>

type CourseVideo struct {
	CourseVideoID     string  `gorm:"column:course_video_id;primaryKey" json:"course_video_id"`
	CourseID          string  `gorm:"column:course_id;" json:"course_id"`
	Username          *string `gorm:"column:username" json:"username"` // 用户昵称
	Path              string  `gorm:"column:path;" json:"path"`
	Size              string  `gorm:"column:size;" json:"size"`
	CourseType        string  `gorm:"column:course_type;" json:"course_type"`
	TrainingProjectID string  `gorm:"column:training_project_id;" json:"training_project_id"`
	CreateTime        *string `gorm:"column:create_time" json:"create_time"`
}

// TableName UserAccount's table name
func (*CourseVideo) TableName() string {
	return TableNameCourseVideo
}

func (*CourseVideo) PrimaryKey() []string {
	return []string{"course_video_id"}
}
