// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTrainingProject = "training_project"

// UserAccount mapped from table <user_account>

type TrainingProject struct {
	TrainingProjectID   string  `gorm:"column:training_project_id;primaryKey" json:"training_project_id"`
	Name                *string `gorm:"column:name" json:"name"` // 用户昵称
	TrainingType        string  `gorm:"column:training_type;not null" json:"training_type"`
	BodyPart            string  `gorm:"column:body_part;not null" json:"body_part"`
	DifficultyLevel     *string `gorm:"column:difficulty_level" json:"difficulty_level"`
	Description         *string `gorm:"column:description" json:"description"`
	ActionStandard      *string `gorm:"column:action_standard" json:"action_standard"` // 用户邮箱
	Precautions         *string `gorm:"column:precautions" json:"precautions"`
	MovieAddress        *string `gorm:"column:movie_address" json:"movie_address"`
	Img1                *string `gorm:"column:img1" json:"img1"`
	IsDelete            *string `gorm:"column:is_delete" json:"is_delete"`
	CreateTime          *string `gorm:"column:create_time" json:"create_time"`
	CreateUser          *string `gorm:"column:create_user" json:"create_user"`
	ModifyTime          *string `gorm:"column:modify_time" json:"modify_time"`
	ModifyUser          *string `gorm:"column:modify_user" json:"modify_user"`
	OrderIndex          *int32  `gorm:"column:order_index" json:"order_index"`
	Icon                *string `gorm:"column:icon" json:"icon"`
	Mp3                 *string `gorm:"column:mp3" json:"mp3"`
	Mp4                 *string `gorm:"column:mp4" json:"mp4"`
	Speed               *string `gorm:"column:speed" json:"speed"`
	SpecialEffects      *string `gorm:"column:special_effects" json:"special_effects"`
	BackgroundModel     *string `gorm:"column:background_model" json:"background_model"`
	BackgroundManImage  *string `gorm:"column:background_man_image" json:"background_man_image"`
	TimeModel           *string `gorm:"column:time_model" json:"time_model"`
	DashboardTime       *string `gorm:"column:dashboard_time" json:"dashboard_time"`
	TrainingProjectCode *string `gorm:"column:training_project_code" json:"training_project_code"`
}

// TableName UserAccount's table name
func (*TrainingProject) TableName() string {
	return TableNameTrainingProject
}

func (*TrainingProject) PrimaryKey() []string {
	return []string{"training_project_id"}
}
