// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserAccount = "user_account"

// UserAccount mapped from table <user_account>
type UserAccount struct {
	UserID      string  `gorm:"column:user_id;primaryKey" json:"user_id"`
	Nick        *string `gorm:"column:nick" json:"nick"` // 用户昵称
	Username    string  `gorm:"column:username;not null" json:"username"`
	Password    string  `gorm:"column:password;not null" json:"password"`
	Status      *string `gorm:"column:status" json:"status"`
	EntryDate   *string `gorm:"column:entry_date" json:"entry_date"`
	Email       *string `gorm:"column:email" json:"email"` // 用户邮箱
	Phone       *string `gorm:"column:phone" json:"phone"`
	LeaveDate   *string `gorm:"column:leave_date" json:"leave_date"`
	IsDelete    *string `gorm:"column:is_delete" json:"is_delete"`
	CreateTime  *string `gorm:"column:create_time" json:"create_time"`
	CreateUser  *string `gorm:"column:create_user" json:"create_user"`
	ModifyTime  *string `gorm:"column:modify_time" json:"modify_time"`
	ModifyUser  *string `gorm:"column:modify_user" json:"modify_user"`
	WorkCode    string  `gorm:"column:work_code" json:"work_code"`
	CreateLdap  *string `gorm:"column:create_ldap" json:"create_ldap"`
	LeaveReason *string `gorm:"column:leave_reason" json:"leave_reason"`
	WechatID    *string `gorm:"column:wechat_id" json:"wechat_id"`
	Weight      *string `gorm:"column:weight" json:"weight"`
	Height      *string `gorm:"column:height" json:"height"`
	Sex         *string `gorm:"column:sex" json:"sex"`
	SportLevel  *string `gorm:"column:sport_level" json:"sport_level"`
}

// TableName UserAccount's table name
func (*UserAccount) TableName() string {
	return TableNameUserAccount
}

func (*UserAccount) PrimaryKey() []string {
	return []string{"userid"}
}
