// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package base

const SysMenuName = "sys_menu"

type SysMenu struct {
	SysMenuID     string  `gorm:"column:sys_menu_id;primaryKey" json:"sys_menu_id"`
	MenuType      *string `gorm:"column:menu_type" json:"menu_type"`       //
	MenuName      *string `gorm:"column:menu_name" json:"menu_name"`       //
	MenuCode      *string `gorm:"column:menu_code" json:"menu_code"`       //
	Icon          *string `gorm:"column:icon" json:"icon"`                 //
	IsIndex       *string `gorm:"column:is_index" json:"is_index"`         //
	RouterGroup   *string `gorm:"column:router_group" json:"router_group"` //
	GroupAPI      *string `gorm:"column:group_api" json:"group_api"`       //
	GroupPath     *string `gorm:"column:group_path" json:"group_path"`     //
	API           *string `gorm:"column:api" json:"api"`                   //
	Data          *string `gorm:"column:data" json:"data"`                 //
	URL           *string `gorm:"column:url" json:"url"`                   //
	InMenu        *string `gorm:"column:in_menu" json:"in_menu"`           //
	IsCommon      *string `gorm:"column:is_common" json:"is_common"`       //
	Description   *string `gorm:"column:description" json:"description"`   //
	OrderIndex    *int32  `gorm:"column:order_index" json:"order_index"`
	CreateTime    *string `gorm:"column:create_time" json:"create_time"`
	CreateUser    *string `gorm:"column:create_user" json:"create_user"`
	ParentID      *string `gorm:"column:parent_id" json:"parent_id"`
	BelongProject *string `gorm:"column:belong_project" json:"belong_project"`
	Type          *string `gorm:"column:type" json:"type"`
}

// TableName UserAccount's table name
func (*SysMenu) TableName() string {
	return SysMenuName
}

func (*SysMenu) PrimaryKey() []string {
	return []string{"sys_menu_id"}
}
