// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package autodesk

const PriceDocProjectName = "price_doc_project"

type PriceDocProject struct {
	PriceDocProjectID string  `gorm:"column:price_doc_project_id;primaryKey" json:"price_doc_project_id"`
	Name              *string `gorm:"column:name" json:"name"`                 // 用户昵称
	CreateTime        *string `gorm:"column:create_time" json:"create_time"`   // 用户昵称
	ProjectName       *string `gorm:"column:project_name" json:"project_name"` // 用户昵称
	OrderIndex        *int32 `gorm:"column:order_index" json:"order_index"`   // 用户昵称

}

// TableName UserAccount's table name
func (*PriceDocProject) TableName() string {
	return PriceDocProjectName
}

func (*PriceDocProject) PrimaryKey() []string {
	return []string{"price_doc_project_id"}
}
