// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package autodesk

const TableNameTbConfig = "tb_config"

// WebshellToken mapped from table <webshell_token>
type TbConfig struct {
	TbConfigID  string  `gorm:"column:tb_config_id;primaryKey" json:"tb_config_id"` // ID
	Name        *string `gorm:"column:name" json:"name"`                            // 描述
	Value       *string `gorm:"column:value" json:"value"`                          // 描述
	Project     *string `gorm:"column:project" json:"project"`
	OrderIndex  *int32  `gorm:"column:order_index" json:"order_index"` // 用户昵称// 描述
	Description *string `gorm:"column:description" json:"description"` // 描述
	CreateTime  *string `gorm:"column:create_time" json:"create_time"` // datetime
	CreateUser  *string `gorm:"column:create_user" json:"create_user"` // 添加人

}

// TableName WebshellToken's table name
func (*TbConfig) TableName() string {
	return TableNameTbConfig
}

func (*TbConfig) PrimaryKey() []string {
	return []string{"tb_config_id"}
}
