// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package autodesk

const TechnicalDocName = "technical_doc"

type TechnicalDoc struct {
	TechnicalDocID string  `gorm:"column:technical_doc_id;primaryKey" json:"price_doc_id"`
	Type           *string `gorm:"column:type" json:"type"` // 用户昵称
	Name           *string `gorm:"column:name" json:"name"` // 用户昵称
	OrderIndex     *int32  `gorm:"column:order_index" json:"order_index"`
	CreateTime     *string `gorm:"column:create_time" json:"create_time"`
	CreateUser     *string `gorm:"column:create_user" json:"create_user"`
	AttachmentPath *string `gorm:"column:attachment_path" json:"attachment_path"`
	ParentID       *string `gorm:"column:parent_id" json:"parent_id"`
}

// TableName UserAccount's table name
func (*TechnicalDoc) TableName() string {
	return TechnicalDocName
}

func (*TechnicalDoc) PrimaryKey() []string {
	return []string{"technical_doc"}
}
