// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sport

const TableNameCourse = "course"

// UserAccount mapped from table <user_account>

type Course struct {
	CourseID     string  `gorm:"column:course_id;primaryKey" json:"course_id"`
	TrainingType *string `gorm:"column:training_type" json:"training_type"` // 用户昵称
	BodyPart     *string `gorm:"column:body_part" json:"body_part"`         // 用户昵称
	TeacherID    string  `gorm:"column:teacher_id;not null" json:"teacher_id"`
	StartTime    string  `gorm:"column:start_time;not null" json:"start_time"`
	CourseStage  string  `gorm:"column:course_stage;" json:"course_stage"`
	IsDelete     *string `gorm:"column:is_delete" json:"is_delete"`
	CreateTime   *string `gorm:"column:create_time" json:"create_time"`
	CreateUser   *string `gorm:"column:create_user" json:"create_user"`
}

// TableName UserAccount's table name
func (*Course) TableName() string {
	return TableNameCourse
}

func (*Course) PrimaryKey() []string {
	return []string{"course_id"}
}
