// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sport

const TableNameCourseGrade = "course_grade"

// UserAccount mapped from table <user_account>

type CourseGrade struct {
	CourseGradeID       string  `gorm:"column:course_grade_id;primaryKey" json:"course_grade_id"`
	CourseID            string  `gorm:"column:course_id;" json:"course_id"`
	Username            *string `gorm:"column:username" json:"username"`                           // 用户昵称
	BeforeCalories      *string `gorm:"column:before_calories" json:"before_calories"`             // 用户昵称
	BeforeScore         *string `gorm:"column:before_score" json:"before_score"`                   // 用户昵称
	BeforeTrainingTimes *string `gorm:"column:before_training_times" json:"before_training_times"` // 用户昵称
	BeforeEvaluate      *string `gorm:"column:before_evaluate" json:"before_evaluate"`             // 用户昵称
	InCalories          *string `gorm:"column:in_calories" json:"in_calories"`                     // 用户昵称
	InScore             *string `gorm:"column:in_score" json:"in_score"`                           // 用户昵称
	InTrainingTimes     *string `gorm:"column:in_training_times" json:"in_training_times"`         // 用户昵称
	InEvaluate          *string `gorm:"column:in_evaluate" json:"in_evaluate"`                     // 用户昵称
	AfterCalories       *string `gorm:"column:after_calories" json:"after_calories"`               // 用户昵称
	AfterScore          *string `gorm:"column:after_score" json:"after_score"`                     // 用户昵称
	AfterTrainingTimes  *string `gorm:"column:after_training_times" json:"after_training_times"`
	AfterEvaluate       *string `gorm:"column:after_evaluate" json:"after_evaluate"`
	CreateTime          *string `gorm:"column:create_time" json:"create_time"`
	DashboardType       *string `gorm:"column:dashboard_type" json:"dashboard_type"`
	TrainingProjectCode *string `gorm:"column:training_project_code" json:"training_project_code"`
}

// TableName UserAccount's table name
func (*CourseGrade) TableName() string {
	return TableNameCourseGrade
}

func (*CourseGrade) PrimaryKey() []string {
	return []string{"course_video_id"}
}
