# 项目点路由
service:
  - name: "登录"
    path: "login/index.yml"
  - name: "码表"
    path: "sys_code/index.yml"
  - name: "菜单"
    path: "menu/index.yml"
  - name: "附件"
    path: "attachment/index.yml"
  - name: "角色菜单"
    path: "role_menu/index.yml"
